from board import board_8_puzzle
from algorithms.algorithms import algorithms
import os
import random

def test_bfs():
    board = board_8_puzzle([[1,2,5], [3,4,0], [6,7,8]])
    # board.shuffle(50)
    print(board)
    solver = algorithms(board)

    result: algorithms.result|None = solver.bfs(False)
    result.save_report("report.txt")

def test_visuals():
    board = board_8_puzzle([[1,2,5], [3,4,0], [6,7,8]])
    solver = algorithms(board)
    result: algorithms.result|None = solver.bfs(True)
    if result:
        result.save_report("output/report.txt")

def test_a_star(visual: bool = False):
    board = board_8_puzzle([[1, 2, 5], [3, 4, 0], [6, 7, 8]])
    solver = algorithms(board)
    result: algorithms.result|None = solver.A_star(visual, heuristic="manhattan")
    if result:
        result.save_report("report.txt")

def compare_a_star_heuristics():
    board = board_8_puzzle([[1, 2, 5], [3, 4, 0], [6, 7, 8]])
    solver = algorithms(board)

    man = solver.A_star(False, heuristic="manhattan")
    euc = solver.A_star(False, heuristic="euclidean")

    def moves_string(result: algorithms.result) -> str:
        if not result.goal_state:
            return "N/A"
        path = result.goal_state.get_path()
        move_map = {"up": "U", "down": "D", "left": "L", "right": "R"}
        moves = [move_map.get(s.move, s.move) for s in path[1:]]
        return " ".join(m for m in moves if m)

    print("A* Heuristic Comparison")
    print("Start board:")
    print(board)
    print("- Manhattan:")
    print(f"  Expanded nodes: {len(man.explored)}")
    print(f"  Cost of path: {man.goal_state.level if man.goal_state else 'N/A'}")
    print(f"  Moves: {moves_string(man)}")
    print(f"  Time: {man.time_taken:.4f} sec")
    print("- Euclidean:")
    print(f"  Expanded nodes: {len(euc.explored)}")
    print(f"  Cost of path: {euc.goal_state.level if euc.goal_state else 'N/A'}")
    print(f"  Moves: {moves_string(euc)}")
    print(f"  Time: {euc.time_taken:.4f} sec")

    if man.goal_state and euc.goal_state:
        if len(man.explored) < len(euc.explored):
            print("Result: Manhattan expanded fewer nodes on this puzzle.")
        elif len(man.explored) > len(euc.explored):
            print("Result: Euclidean expanded fewer nodes on this puzzle.")
        else:
            print("Result: Both expanded the same number of nodes on this puzzle.")

    print("Note: For the 8-puzzle, both Manhattan and Euclidean are admissible heuristics.")
    print("(On very easy boards, they can expand the same number of nodes.)")


def compare_a_star_heuristics_shuffled(shuffle_moves: int = 25, seed: int = 0):
    """Compare heuristics on a harder, reproducible shuffled board."""
    random.seed(seed)
    base = board_8_puzzle()  # starts at goal
    base.shuffle(shuffle_moves)

    start_matrix = [row.copy() for row in base.board]
    man_board = board_8_puzzle([row.copy() for row in start_matrix])
    euc_board = board_8_puzzle([row.copy() for row in start_matrix])

    man = algorithms(man_board).A_star(False, heuristic="manhattan")
    euc = algorithms(euc_board).A_star(False, heuristic="euclidean")

    def moves_string(result: algorithms.result) -> str:
        if not result.goal_state:
            return "N/A"
        path = result.goal_state.get_path()
        move_map = {"up": "U", "down": "D", "left": "L", "right": "R"}
        moves = [move_map.get(s.move, s.move) for s in path[1:]]
        return " ".join(m for m in moves if m)

    print("A* Heuristic Comparison (Shuffled)")
    print(f"Shuffle moves: {shuffle_moves}, seed: {seed}")
    print("Start board:")
    print(man_board)
    print("- Manhattan:")
    print(f"  Expanded nodes: {len(man.explored)}")
    print(f"  Cost of path: {man.goal_state.level if man.goal_state else 'N/A'}")
    print(f"  Moves: {moves_string(man)}")
    print(f"  Time: {man.time_taken:.4f} sec")
    print("- Euclidean:")
    print(f"  Expanded nodes: {len(euc.explored)}")
    print(f"  Cost of path: {euc.goal_state.level if euc.goal_state else 'N/A'}")
    print(f"  Moves: {moves_string(euc)}")
    print(f"  Time: {euc.time_taken:.4f} sec")

    if man.goal_state and euc.goal_state:
        if len(man.explored) < len(euc.explored):
            print("Result: Manhattan expanded fewer nodes on this puzzle.")
        elif len(man.explored) > len(euc.explored):
            print("Result: Euclidean expanded fewer nodes on this puzzle.")
        else:
            print("Result: Both expanded the same number of nodes on this puzzle.")

    print("Note: Both heuristics are admissible; Manhattan is usually more informed.")


def compare_a_star_heuristics_with_visuals(shuffle_moves: int | None = None, seed: int = 0):
    """Generate visualizer PNGs for both heuristics.

    If shuffle_moves is provided, the start board is generated by shuffling the goal
    state by that many random moves (reproducible via seed).
    """
    if shuffle_moves is None:
        start_matrix = [[1, 2, 5], [3, 4, 0], [6, 7, 8]]
        tag = "base"
    else:
        random.seed(seed)
        base = board_8_puzzle()  # starts at goal
        base.shuffle(shuffle_moves)
        start_matrix = [row.copy() for row in base.board]
        tag = f"shuffled_{shuffle_moves}_seed{seed}"

    man_board = board_8_puzzle([row.copy() for row in start_matrix])
    euc_board = board_8_puzzle([row.copy() for row in start_matrix])

    man_dir = os.path.join("output", tag, "manhattan")
    euc_dir = os.path.join("output", tag, "euclidean")

    print("Visual start board:")
    print(man_board)

    print(f"Generating visuals for Manhattan in: {man_dir}")
    algorithms(man_board).A_star(True, heuristic="manhattan", output_dir=man_dir)
    print(f"Generating visuals for Euclidean in: {euc_dir}")
    algorithms(euc_board).A_star(True, heuristic="euclidean", output_dir=euc_dir)

if __name__ == "__main__":
    # Runs all A* comparisons + visuals in one go
    print("=" * 60)
    compare_a_star_heuristics()
    print("=" * 60)
    compare_a_star_heuristics_shuffled()
    print("=" * 60)
    # Visuals can generate lots of images; keep shuffle_moves small.
    compare_a_star_heuristics_with_visuals(shuffle_moves=10, seed=0)

